#!/bin/sh
#
# Usage: ./maketar [-rTAG]

PROJECT_NAME=popbsmtp
TAR_NAME=pop-before-smtp

cvs co -P "$@" $PROJECT_NAME

cd $PROJECT_NAME || exit 1

# Support making the tar file with a temporary patch.
if test -f ../patch ; then
    patch -p0 <../patch
fi

ver=`sed -ne "s/^my .VERSION = '\([^']*\).*/\1/p" pop-before-smtp`

rm -rf pkg CVS */CVS */*/CVS .cvsignore */.cvsignore */*/.cvsignore

cd ..

mv $PROJECT_NAME $TAR_NAME-$ver
if test -f $TAR_NAME-$ver.tar.gz; then
    fakeroot tar cvfz $TAR_NAME-cvs.tar.gz $TAR_NAME-$ver
else
    fakeroot tar cvfz $TAR_NAME-$ver.tar.gz $TAR_NAME-$ver
fi
rm -rf $TAR_NAME-$ver
